# Generated by Django 4.2.6 on 2024-02-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outil',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='photooutil',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fabrique.outil', verbose_name='outil'),
        ),
    ]
