# Generated by Django 4.2.6 on 2024-02-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0003_alter_client_address_alter_client_cni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoclient',
            old_name='representant',
            new_name='client',
        ),
    ]
