# Generated by Django 4.2.6 on 2024-02-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0004_rename_representant_photoclient_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoclient',
            options={'verbose_name_plural': 'Photos Clients'},
        ),
        migrations.AlterModelOptions(
            name='photorepresentantclient',
            options={'verbose_name_plural': 'Photos Representants Clients'},
        ),
    ]
