# Generated by Django 4.2.6 on 2024-02-10 06:29

from django.db import migrations, models
import ets_alexis.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0005_alter_photoclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photoclient',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photorepresentantclient',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='representantclient',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
