# Generated by Django 4.2.6 on 2024-02-10 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0006_alter_client_id_alter_photoclient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
