# Generated by Django 4.2.6 on 2024-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0007_client_creation_date_client_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='pseudo',
            field=models.CharField(default='Employer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='firstName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
