# Generated by Django 4.2.6 on 2024-02-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0008_employer_pseudo_alter_employer_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
