# Generated by Django 4.2.6 on 2024-02-11 00:53

from django.db import migrations, models
import ets_alexis.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0009_alter_employer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photoemployer',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
