# Generated by Django 4.2.6 on 2024-02-11 02:33

from django.db import migrations, models
import ets_alexis.utils


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0010_alter_employer_id_alter_photoemployer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoprestataire',
            old_name='representant',
            new_name='prestataire',
        ),
        migrations.AlterField(
            model_name='photoprestataire',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photorepresentantprestataire',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='role',
            field=models.CharField(choices=[('Representant', 'Representant'), ('Responsable', 'Responsable'), ('Propriétaire', 'Propriétaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='representantprestataire',
            name='id',
            field=models.CharField(default=ets_alexis.utils.get_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
