# Generated by Django 4.2.6 on 2024-02-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0011_rename_representant_photoprestataire_prestataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantprestataire',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='representantprestataire',
            name='cni',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='representantprestataire',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
