# Generated by Django 4.2.6 on 2024-02-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0012_alter_representantprestataire_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoarticle',
            options={'verbose_name': 'Photos Articles'},
        ),
        migrations.AlterModelOptions(
            name='photoemployer',
            options={'verbose_name': 'Photos Employers'},
        ),
        migrations.AlterModelOptions(
            name='photooutil',
            options={'verbose_name': 'Photos Outils'},
        ),
        migrations.AlterModelOptions(
            name='photoprestataire',
            options={'verbose_name': 'Photos Prestataires'},
        ),
        migrations.AlterModelOptions(
            name='photorepresentantprestataire',
            options={'verbose_name': 'Photos Représentants Prestataires'},
        ),
        migrations.RenameField(
            model_name='photooutil',
            old_name='representant',
            new_name='outil',
        ),
    ]
