# Generated by Django 4.2.6 on 2024-02-11 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrique', '0013_alter_photoarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photooutil',
            name='outil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fabrique.outil'),
        ),
    ]
